name: Build and deploy Python app to Azure Web App - baymaxbackend

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Set environment variables
        run: |
          echo "OPENAI_API_TYPE=${{ secrets.OPENAI_API_TYPE }}" >> .env
          echo "OPENAI_API_VERSION=${{ secrets.OPENAI_API_VERSION }}" >> .env
          echo "OPENAI_API_BASE=${{ secrets.OPENAI_API_BASE }}" >> .env
          echo "OPENAI_API_DEPLOYMENT=${{ secrets.OPENAI_API_DEPLOYMENT }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Zip artifact for deployment
        run: zip release.zip backend/* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F26F2644A84947B084D79E33C9704F43 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DA57C46020FE41C09DCC7B6D68E9A42A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54A4B675B2B947168E99AE61506559E1 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "baymaxbackend"
          slot-name: "Production"
